= Rapport d’avancement du groupe “3.3”
PACT groupe 33
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]
:doctype: book
:stem: latexmath
:source-highlighter: coderay
:toc-title: Table des matières
:toc: macro
:sectnums:
:imagesdir: images


// Partie non numérotée
:sectnums!:
== « Nom du groupe »
E-POKAMP

=== Membres du groupe

* Glasziou Erwan
* Bouffant Charles
* Dulout Eugénie
* Bruno François
* Audinet Quentin
* Bakache Victor
* Boutaj Sofiene
* Senane Zineb

=== Tuteur

* JABBOUR Chadi

=== Encadrant génie logiciel

* MOISSINAC Jean-Claude

== Résumé du sujet choisi en français (PAN1)

*_Note: 15 lignes max_*

Décrire votre projet sans le scénariser : De quoi s’agit-il ? En quoi
cette idée est compatible avec le thème de PACT ? Qu’est ce qu’il
permettrait de faire de façon générale.

Il s'agit d'une application de création de liste de courses reliée à une base de donnée des produits disponibles en magasin, associée à une méthode de localisation à l'intérieur du magasin. Lors de la création de la liste, l'application propose des produits en fonction des préférences de l'utilisateur et de ses listes précédentes, mais aussi des promotions actuelles dans le magasin. 
Les listes de courses peuvent être partagées entre utilisateurs, ainsi que des sous-listes (ou "recettes") de type d'ingrédients, ce qui est utile au sein d'un foyer par exemple. Une fois la liste de courses rentrée et dans le magasin, l'application fournit la localisation de l'usager et des produits sur la listes, ainsi qu'un chemin optimal pour aller les récupérer. 
Le recensement des produits et de leur localisation se fait de manière participative par les utilisateurs.
De plus, notre projet n'a pas pour unique objectif de guider les clients dans leur magasin afin de rendre leurs courses moins pénibles. L'application devra aussi permettre à l'utilisateur de pouvoir adopter (s'il le souhaite) un mode de consommation sain et responsable. Lorsque l'utilisateur choisit un produit à ajouter à sa liste, l'application devra lui proposer les différents produits disponibles, classés selon ses préférences (prix, bio, local, sain...).
Dès lors, notre projet se place au service de l'humain en aidant l'utilisateur à prendre soin de sa santé, les commerçants locaux à vivre et vendre leurs produits, et la planète en luttant contre le gaspillage et en valorisant l'agriculture biologique.  


== English Summary (PAN1)

*_Note : 15 lignes max, version anglaise du texte précédent_*

Ligula dapibus egestas. Donec sed velit ac lectus mattis sagittis.

In hac habitasse platea dictumst. Maecenas in ligula. Duis tincidunt
odio sollicitudin quam. Nullam non mauris. Phasellus lacinia, velit sit
amet bibendum euismod, leo diam interdum ligula, eu scelerisque sem
purus in tellus.

*Notes concenant le rapport*

Les différentes pages du document sont rédigées en utilisant le langage
AsciiDoc. Le squelette de rapport contient des exemples avec entre autre:

* des images,
* des liens,
* des équations.

La structure du rapport (parties, sections et la relation avec les
differents fichiers) se trouve dans le fichier courant.

// en PDF on ne peut pas controler la position de la toc
// Macros non supportées
ifndef::backend-pdf[]
== Table des matières
:toc-title:
toc::[]
endif::[]

// On numérote le reste des sections
:sectnums:

== Étude d’antériorité et justification de la proposition (PAN1)

include::proposition/proposition.adoc[Description de la proposition]

include::proposition/etat-de-l-art.adoc[Description de l’état de l’art]

== Scénarios d’usage (PAN1)

include::scenario/scenario.adoc[Scénarios d’usage]

<<<

== Architecture du projet (PAN1)

include::architecture/schema.adoc[Schéma d’architecture]

include::architecture/interfaces.adoc[Description des interfaces]

include::architecture/sequence.adoc[Diagramme de séquence]

include::architecture/ihm.adoc[Interface utilisateur graphique]

include::architecture/taches.adoc[Tableau détaillé des tâches]

<<<

== Organisation du projet (PAN1)

include::organisation/planification.adoc[Diagramme de planification temporel des tâches]

include::organisation/repartition.adoc[Répartition des élèves par module]

include::organisation/plan-tests.adoc[Plans de test (PAN2+)]

<<<

[bibliography]
== Bibliographie (PAN1+)

include::References.adoc[Bibliographie]

<<<

== Annexes

include::annexes/modifications.adoc[Modifications (PAN2+)]

include::annexes/avancement.adoc[Avancement des modules]

include::annexes/moduleX.adoc[Avancement module X]

include::annexes/moduleY.adoc[Avancement module Y]
