=== Plans de test (PAN2+)

Vous allez travailler sur chaque bloc de votre projet, et qu’il soit
informatique, électronique ou matériel, vous allez devoir faire du
test :

* tester que le bloc que vous venez de finir fait ce qu’il faut ;
* tester que le bloc fonctionne avec les blocs en amont ou en aval dans
l’architecture ;
* tester que les performances sont acceptables…
* et plus globalement, tester que le projet « marche ».

Vous allez devoir faire ce travail sur le prototype allégé, puis sur le
prototype final. C’est un travail dans le module « intégration et
tests ».

Cette section rassemble les plans de test du proto allégé et du proto
final. C’est une liste des tests à effectuer, sous la forme, pour chaque
test :

* situation/contexte
* action ou entrée à appliquer
* réaction ou sortie attendue.

==== Plan de test allégé

* Test Barcode-Android

**Situation**

On a un code barre que l'on peut lire (et donc une sortie du module). Vérifier si le module Android réagit correctement (affichage du bon produit).

**action ou entrée à appliquer**

Scan d'un code barre et/ou variable en sortie du module.

**réaction ou sortie attendue**

Requête à la BDD correspondant au bon produit/ affichage du produit.

* Test Plan-Android

**Situation**

On vérifie l'affichage correcte du module plan dans l'appli.

**action ou entrée à appliquer**

WIP : En attente du module Plan.

**réaction ou sortie attendue**

Affichage du plan 3D au sein de l'appli.

* Test BDD-Android

**Situation**

On veut récupérer les produits qui sont en stock,ou bien une liste/recette de l'un des amis. On vérifie si les deux modules réagissent correctement entre eux.

**action ou entrée à appliquer**

Taper le nom du produit / ami.

**réaction ou sortie attendue**

Réception et affichage des produits / listes / recettes correspondants.

* Test BDD-Algorythme

**Situation**

Le Serveur reçoit une requête et la relai à l'algorythme de recherche 

**action ou entrée à appliquer**

Requête de l'appli/Interface WEB.

**réaction ou sortie attendue**

Réponse correspondant à la requête.


