=== Description de l’état de l’art
ifdef::env-gitlab,env-browser[:outfilesuffix: .adoc]


==== Aisle411

Comme expliqué dans <<Aisle411>>, Aisle411 est une application développée en Amérique et qui est déployée dans plus de 14 000 lieux de vente, de bureaux ou  d'aéroports. Cette application indique à un utilisateur l'emplacement de l'objet de leur choix dans un magasin particulier. Les utilisateurs peuvent également utiliser l'application pour scanner les codes barres afin de lire les avis sur les produits et de découvrir les remises et les promotions en magasin. 

Une des différences majeures avec notre projet est que le "GPS" donne une vision 3D à l'utilisateur tout au long de son trajet dans le magasin. Contrairement à cette application, nous envisageons d'afficher une vision 2D à l'utilisateur lorsque celui-ci navigue dans les rayons, puis basculer en 3D lorsque l'utilisateur se trouve près du produit afin de mieux le guider vers celui-ci. De plus, la dimension environnementale n'est pas prise en compte dans l'application contrairement à notre projet qui essaie au mieux de traiter cette problématique. Pour finir, notre application possède beaucoup de fonctionnalités en plus telles que la possibilité de partager des recettes avec ses amis ou encore l'algorithme de suggestions intelligentes.

==== Applications android

D’autres applications sont disponibles sur le PlayStore et permettent de réaliser quelques-unes des composantes de notre projet. Yuka est une application qui permet de scanner le code-barre de n’importe quel produit alimentaire pour obtenir sa composition et lui attribuer un score relatif à son impact sur notre santé. L’appli des Consos C&C, Karbon ou encore BuyOrNot permettent, toujours en scannant le code barre d’un produit, d’afficher de très nombreuses informations sur ses impacts économiques, sociaux, sanitaires et environnementaux ainsi que sur son entreprise. 
